analytics: {}
color:
  brandColors:
    - '#29272C'
    - '#FFFDFF'
    - '#969497'
    - '#B5B3B7'
    - '#5E5C61'
  brandStrength: 0
  lightness: 0
  rhythmicContrast: 0
  saturation: 0
cta: {}
layout_spectrum: 0.5304
name: TuyoIsaza
opengraph: {}
purpose: []
typography_spectrum: 0
