name: TuyoIsaza
favicon: null
layout_spectrum: 0.50452
typography_spectrum: 0.5370049732737243
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#29272c'
    - '#fffdff'
    - '#969497'
    - '#b5b3b7'
    - '#5e5c61'
  brandStrength: 0.3626036932691932
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0.30902153393253684
purpose: []
