name: TuyoIsaza
favicon: null
layout_spectrum: 0.7501715836115181
typography_spectrum: 0.5370049732737243
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3626036932691932
  lightness: 0.7284604110755026
  saturation: 0.1360018695704639
  rhythmicContrast: 0.30902153393253684
purpose: []
